#!/bin/bash

# THERE ARE FOUR SPECIAL PARAMETERS $0 & $# ,$* ,$@

# $# : HOLDS HOW MANY ARGUMENT ARE GIVEN TO ACERTAIN CMD
echo "result of \$# : $#"

# #0 : EXPANDS TO THE VALUE OF THE NAME OF CURRENT SCRIPT WHEN USED IN A SCRIPT AND TO BASH WHEN USED  DIRECTLY IN BASH
echo "result of \$0 : $0"

# $@ : LIST ALL TYPED PARAMETERS
echo "result of \$* : $*"

# $* : UNQUOTED $* IS THE SAME AS $@ WHERE "$*" PLACE THE FIRSTCHAR OF THE IFS VARIABLE WHEN LISTING ARGUMENT
echo "result of \$@ : $@"

#POSITIONAL PARAMS ARE READ AT THT ORDER THEY ARE GIVEN TO A CERTAIN CMD
echo "hi there $1,$2"
IFS=,
touch $*

exit 0
